project:
  type: website
  output-dir: docs
website:
  title: "LUIS ORTIZ CEVALLOS"
  image: "Luis.png"
  favicon: "Luis.png"
  navbar:
    right:
      - icon: github
        href: https://github.com/Ortiz-Cevallos

lang: es
format:
  html:
    theme: pulse
    css: styles.css
    code-fold: true
    include-after-body: graph_fold.html

editor: visual

